name: Feature request
description: Suggest a new feature for Tukaan
labels: ["enhancement"]

body:
  - type: textarea
  id: description
  attributes:
    label: "What's feature request"
    description: |
      Describe what new feature you would like to see in Tukaan.
  validations:
    required: false
    
  - type: textarea
  id: alternatives
  attributes:
    label: "Alternatives you've considered"
    description: |
      A clear and concise description of any alternative solutions or features you have considered.
      "There should be one - and preferably only one - obvious way to do it, although that way may not be obvious at first."
  validations:
    required: true
