on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Install black
    - run: pip install black
    - run: python3 -m black --check tukaan/*.py
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Install isort
    - run: pip install isort
    - run: python3 -m isort --check tukaan/*.py
